services:
  alejoide-tech:
    image: alejoide/alejoide-tech:latest
    container_name: alejoide-tech
    restart: unless-stopped
    env_file:
      - ./config/web/.env
    networks:
      - internal

  nginx:
    image: nginx:1.29-alpine
    container_name: alejoide-tech-nginx
    env_file:
      - ./config/nginx/.env
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
    restart: always
    depends_on:
      - alejoide-tech
    networks:
      - nginx-proxy

volumes:
  projects-api-data:
    name: projects-api-data

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
