services:
  alejoide-tech:
    image: alejoide/alejoide-tech:latest
    container_name: alejoide-tech
    restart: unless-stopped
    env_file:
      - ./config/web/.env
    networks:
      - nginx-proxy
      - default

networks:
  nginx-proxy:
    name: nginx-proxy
    external: true
